defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: blueruby
  password: uberhum0n
  socket: /var/run/mysqld/mysqld.sock

development:
  database: vfitour_development
<<: *defaults

test:
  database: vfitour_test
<<: *defaults

production:
  database: vfitour_production
<<: *defaults

